[project]
name = "customtkinter-mvp-crud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=6.0.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
    "pytest>=9.1.1",
    "pytest-mock>=3.15.1",
]
